(function () {
  const fallbackMenu = [
    {
      _id: "m1",
      name: "Jerk Chicken Lunch Box",
      category: "Lunch Boxes",
      description: "Smoky jerk chicken with rice, cabbage and plantain.",
      price: 1800,
      accent: "Customer favorite",
      imageUrl: "assets/images/lunch-box/branded-jerk-chicken-box.webp",
      isAvailable: true,
      isFeatured: true,
      categorySortOrder: 1,
      sortOrder: 1,
    },
    {
      _id: "m2",
      name: "Curry Chicken Lunch Box",
      category: "Lunch Boxes",
      description: "Slow-cooked curry chicken served with rice and a seasonal side.",
      price: 1800,
      accent: "Comfort food",
      imageUrl: "assets/images/lunch-box/branded-curry-chicken-box.webp",
      isAvailable: true,
      isFeatured: true,
      categorySortOrder: 1,
      sortOrder: 2,
    },
    {
      _id: "m3",
      name: "Escovitch Fish Lunch Box",
      category: "Lunch Boxes",
      description: "Seasoned fish finished with bright pickled peppers and vegetables.",
      price: 2400,
      accent: "Made fresh",
      imageUrl: "assets/images/lunch-box/branded-escovitch-fish.webp",
      isAvailable: true,
      categorySortOrder: 1,
      sortOrder: 3,
    },
    {
      _id: "m4",
      name: "Steamed Fish Lunch Box",
      category: "Lunch Boxes",
      description: "Whole fish steamed with herbs, peppers and garden vegetables.",
      price: 2600,
      accent: "Cooked to order",
      isAvailable: true,
      categorySortOrder: 1,
      sortOrder: 4,
    },
    {
      _id: "m5",
      name: "Callaloo",
      category: "Sides",
      description: "Tender greens cooked with fresh vegetables and island seasoning.",
      price: 700,
      isAvailable: true,
      categorySortOrder: 5,
      sortOrder: 5,
    },
    {
      _id: "m6",
      name: "Fried Dumplings",
      category: "Sides",
      description: "Golden, crisp outside and soft inside. Three per order.",
      price: 600,
      isAvailable: true,
      categorySortOrder: 5,
      sortOrder: 6,
    },
    {
      _id: "m7",
      name: "Build Your Lunch Box",
      category: "Build Your Own",
      description: "Choose a main, rice and side to make the box yours.",
      price: 1700,
      isAvailable: true,
      isCustomDrink: true,
      showsStartingPrice: true,
      categorySortOrder: 2,
      sortOrder: 7,
      optionGroups: [
        {
          _id: "g-main",
          name: "Choose your main",
          description: "One main is included.",
          selectionMode: "single",
          minSelections: 1,
          maxSelections: 1,
          options: [
            { id: "jerk-chicken", name: "Jerk chicken", description: "", price: 0 },
            { id: "curry-chicken", name: "Curry chicken", description: "", price: 0 },
            { id: "fish", name: "Fish", description: "", price: 700 },
          ],
        },
        {
          _id: "g-side",
          name: "Choose your side",
          description: "Pick one included side.",
          selectionMode: "single",
          minSelections: 1,
          maxSelections: 1,
          options: [
            { id: "callaloo", name: "Callaloo", description: "", price: 0 },
            { id: "plantain", name: "Plantain", description: "", price: 0 },
            { id: "dumplings", name: "Fried dumplings", description: "", price: 200 },
          ],
        },
      ],
    },
    {
      _id: "m8",
      name: "Jerk Chicken Catering Tray",
      category: "Catering Trays",
      description: "A party-ready tray of chopped jerk chicken.",
      price: 8500,
      imageUrl: "assets/images/lunch-box/branded-jerk-chicken.webp",
      isAvailable: true,
      isBottleService: true,
      categorySortOrder: 8,
      sortOrder: 8,
    },
    {
      _id: "m9",
      name: "Fish & Vegetable Catering Tray",
      category: "Catering Trays",
      description: "Seasoned fish with peppers and vegetables for group orders.",
      price: 12000,
      imageUrl: "assets/images/lunch-box/branded-escovitch-fish.webp",
      isAvailable: true,
      isBottleService: true,
      categorySortOrder: 8,
      sortOrder: 9,
    },
    {
      _id: "m10",
      name: "Soup",
      category: "Starters",
      description: "A comforting bowl of today's freshly prepared soup.",
      price: 500,
      isAvailable: true,
      categorySortOrder: 3,
      sortOrder: 10,
    },
    {
      _id: "m11",
      name: "Jerk Chicken",
      category: "Mains",
      description: "Chicken seasoned with our bold jerk spices and cooked until tender.",
      price: 1000,
      imageUrl: "assets/images/lunch-box/branded-jerk-chicken.webp",
      isAvailable: true,
      categorySortOrder: 4,
      sortOrder: 11,
    },
    {
      _id: "m12",
      name: "Jerk Pork",
      category: "Mains",
      description: "Tender pork seasoned with our bold jerk spices.",
      price: 1000,
      isAvailable: true,
      categorySortOrder: 4,
      sortOrder: 12,
    },
    {
      _id: "m13",
      name: "Fish",
      category: "Mains",
      description: "Freshly prepared fish in your choice of size.",
      price: 2500,
      isAvailable: true,
      showsStartingPrice: true,
      categorySortOrder: 4,
      sortOrder: 13,
      optionGroups: [
        {
          _id: "g-fish-size",
          name: "Choose your fish size",
          description: "Select a regular or large fish.",
          selectionMode: "single",
          minSelections: 1,
          maxSelections: 1,
          options: [
            { id: "regular", name: "Regular", description: "$25 size", price: 0 },
            { id: "large", name: "Large", description: "$30 size", price: 500 },
          ],
        },
      ],
    },
    {
      _id: "m14",
      name: "Rice & Peas Meal",
      category: "Mains",
      description: "A hearty meal built around seasoned rice and peas.",
      price: 1500,
      isAvailable: true,
      categorySortOrder: 4,
      sortOrder: 14,
    },
    {
      _id: "m15",
      name: "Festival",
      category: "Sides",
      description: "Sweet Jamaican fried dough with a golden outside and soft center.",
      price: 500,
      imageUrl: "assets/images/lunch-box/branded-festival.webp",
      isAvailable: true,
      categorySortOrder: 5,
      sortOrder: 15,
    },
    {
      _id: "m16",
      name: "Fried Plantain",
      category: "Sides",
      description: "Sweet ripe plantain fried until caramelized.",
      price: 500,
      isAvailable: true,
      categorySortOrder: 5,
      sortOrder: 16,
    },
    {
      _id: "m17",
      name: "Strawberry Pineapple",
      category: "Natural Drinks",
      description: "A refreshing natural strawberry and pineapple drink.",
      price: 1000,
      isAvailable: true,
      categorySortOrder: 6,
      sortOrder: 17,
    },
    {
      _id: "m18",
      name: "To The World",
      category: "Natural Drinks",
      description: "The house natural drink blend featured on our menu.",
      price: 1000,
      isAvailable: true,
      categorySortOrder: 6,
      sortOrder: 18,
    },
    {
      _id: "m19",
      name: "Beetroot",
      category: "Natural Drinks",
      description: "A vibrant natural beetroot drink.",
      price: 1000,
      isAvailable: true,
      categorySortOrder: 6,
      sortOrder: 19,
    },
    {
      _id: "m20",
      name: "Irish Moss",
      category: "Natural Drinks",
      description: "A rich, creamy Caribbean-style Irish moss drink.",
      price: 1000,
      isAvailable: true,
      categorySortOrder: 6,
      sortOrder: 20,
    },
    {
      _id: "m21",
      name: "Cucumber",
      category: "Natural Drinks",
      description: "A cool and refreshing natural cucumber drink.",
      price: 1000,
      isAvailable: true,
      categorySortOrder: 6,
      sortOrder: 21,
    },
    {
      _id: "m22",
      name: "Carrot",
      category: "Natural Drinks",
      description: "A smooth natural carrot drink with island flavor.",
      price: 1000,
      isAvailable: true,
      categorySortOrder: 6,
      sortOrder: 22,
    },
    {
      _id: "m23",
      name: "Other Natural Drink",
      category: "Natural Drinks",
      description: "Ask about today's additional natural drink flavor.",
      price: 1000,
      isAvailable: true,
      categorySortOrder: 6,
      sortOrder: 23,
    },
  ];

  fallbackMenu.find((item) => item.name === "Soup").sizes = [{ name: "Small", price: 500 }, { name: "Large", price: 1000 }];
  const fish = fallbackMenu.find((item) => item.name === "Fish");
  fish.sizes = [{ name: "Small", price: 2500 }, { name: "Large", price: 3000 }];
  fish.optionGroups = [];
  fallbackMenu.push(
    { _id: "m24", name: "Jerk Pork Lunch Box", category: "Lunch Boxes", description: "Smoky jerk pork with rice and peas, cabbage and plantain.", price: 1800, isAvailable: true, categorySortOrder: 1, sortOrder: 5 },
    { _id: "m25", name: "Jerk Pork Catering Tray", category: "Catering Trays", description: "A generous tray of tender, smoky jerk pork for your whole group.", price: 8500, isAvailable: true, isBottleService: true, categorySortOrder: 8, sortOrder: 10 }
  );

  const fallbackEvents = [
    {
      _id: "e1",
      title: "Lunch Box Pop-Up",
      date: "2026-09-05",
      startTime: "12:00 PM",
      endTime: "5:00 PM",
      description: "A sample announcement ready to replace with the next Lunch Box pop-up, special or catering date.",
      imageUrl: "assets/images/lunch-box/garett-grilling.webp",
      isPublished: true,
    },
  ];

  const brandedMenuImages = {
    "Jerk Pork Lunch Box": "assets/images/lunch-box/branded-jerk-pork-box.webp",
    "Jerk Pork Catering Tray": "assets/images/lunch-box/branded-jerk-pork-catering.webp",
    "Jerk Chicken Lunch Box": "assets/images/lunch-box/branded-jerk-chicken-box.webp",
    "Curry Chicken Lunch Box": "assets/images/lunch-box/branded-curry-chicken-box.webp",
    "Escovitch Fish Lunch Box": "assets/images/lunch-box/branded-escovitch-fish.webp",
    "Steamed Fish Lunch Box": "assets/images/lunch-box/branded-steamed-fish-box-v2.webp",
    "Callaloo": "assets/images/lunch-box/branded-callaloo-v2.webp",
    "Fried Dumplings": "assets/images/lunch-box/branded-fried-dumplings-v2.webp",
    "Jerk Chicken": "assets/images/lunch-box/branded-jerk-chicken.webp",
    "Soup": "assets/images/lunch-box/branded-soup-v2.webp",
    "Jerk Pork": "assets/images/lunch-box/branded-jerk-pork-v2.webp",
    "Fish": "assets/images/lunch-box/branded-cooked-fish.webp",
    "Rice & Peas Meal": "assets/images/lunch-box/branded-rice-and-peas-v2.webp",
    "Festival": "assets/images/lunch-box/branded-festival.webp",
    "Fried Plantain": "assets/images/lunch-box/branded-fried-plantain-v2.webp",
    "Strawberry Pineapple": "assets/images/lunch-box/branded-strawberry-pineapple-v2.webp",
    "To The World": "assets/images/lunch-box/branded-to-the-world-v2.webp",
    "Beetroot": "assets/images/lunch-box/branded-beetroot-v2.webp",
    "Irish Moss": "assets/images/lunch-box/branded-irish-moss-v2.webp",
    "Cucumber": "assets/images/lunch-box/branded-cucumber-v2.webp",
    "Carrot": "assets/images/lunch-box/branded-carrot-v2.webp",
    "Other Natural Drink": "assets/images/lunch-box/branded-other-natural-v2.webp",
    "Jerk Chicken Catering Tray": "assets/images/lunch-box/branded-jerk-chicken.webp",
    "Fish & Vegetable Catering Tray": "assets/images/lunch-box/branded-escovitch-fish.webp",
  };
  const knownMenuNames = new Set(fallbackMenu.map((item) => item.name));
  const applyBrandImages = (items) =>
    items.map((item) =>
      knownMenuNames.has(item.name)
        ? { ...item, imageUrl: brandedMenuImages[item.name] }
        : item,
    );

  window.LunchBoxData = {
    fallbackMenu: applyBrandImages(fallbackMenu),
    fallbackEvents,
    applyBrandImages,
  };
})();
